import time
import os

os.system('clear')
print("feliz natal e ano novo para você Guilherme!")
time.sleep(3)
os.system('clear')

senha = input("digite a senha: ")

if(senha=="guilhermefoda"):
	os.system('clear')
	print("Processando a senha - ")
	time.sleep(0.5)
	os.system('clear')
	print("prOcessando a senha \ ")
	time.sleep(0.5)
	os.system('clear')
	print("procEssando a senha | ")
	time.sleep(0.5)
	os.system('clear')
	print("procesSando a senha / ")
	time.sleep(0.5)
	os.system('clear')
	print("processaNdo a senha - ")
	time.sleep(0.5)
	os.system('clear')
	print("processando A senha \ ")
	time.sleep(0.5)
	os.system('clear')
	print("processando a sEnha | ")
	time.sleep(0.5)
	os.system('clear')
	print("processando a senHa / ")
	time.sleep(0.5)
	os.system('clear')
	print("processando a senha - ")
	time.sleep(0.5)
	os.system('clear')
	time.sleep(0.5)
	print("senha correta: " + senha)
	time.sleep(2)
	os.system('clear')
	time.sleep(2)
	print("────────────────────────")
	print("╔══╗╔═╦═╗╔══╗╔══╗╔═╗╔══╗")
	print("║╔╗║║║║║║╚║║╝║╔═╣║║║║══╣")
	print("║╠╣║║║║║║╔║║╗║╚╗║║║║╠══║")
	print("╚╝╚╝╚╩═╩╝╚══╝╚══╝╚═╝╚══╝")
	print("────────────────────────")
	print(" ")
	time.sleep(2)
	print("Estamos completando quase 1 ano de amizade!!")
	print(" ")
	time.sleep(2)
	print("Valeu por tudo maninho")
	time.sleep(3.5)
	os.system('clear')
	print("Você é nota ",end='')
	time.sleep(1)
	print('1',end='')
	time.sleep(0.3)
	print('0',end='')
	time.sleep(0.3)
	print('0',end='')
	time.sleep(0.3)
	print('0',end='')
	time.sleep(0.3)
	print('0',end='')
	time.sleep(0.3)
	print('0',end='')
	time.sleep(0.3)
	print('0',end='')
	time.sleep(0.3)
	print('0',end='')
	time.sleep(0.3)
	print('0',end='')
	time.sleep(0.3)
	print('0')
	
	
else:
	os.system('clear')
	print("Processando a senha - ")
	time.sleep(0.5)
	os.system('clear')
	print("prOcessando a senha \ ")
	time.sleep(0.5)
	os.system('clear')
	print("procEssando a senha | ")
	time.sleep(0.5)
	os.system('clear')
	print("procesSando a senha / ")
	time.sleep(0.5)
	os.system('clear')
	print("processaNdo a senha - ")
	time.sleep(0.5)
	os.system('clear')
	print("processando A senha \ ")
	time.sleep(0.5)
	os.system('clear')
	print("processando a sEnha | ")
	time.sleep(0.5)
	os.system('clear')
	print("processando a senHa / ")
	time.sleep(0.5)
	os.system('clear')
	print("processando a senha - ")
	time.sleep(0.5)
	os.system('clear')
	time.sleep(0.5)
	print("senha incorreta: " + senha)
	time.sleep(2)
	os.system('clear')
	print("encerrando...")
	time.sleep(2)
	os.system('clear')
